### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by czue** [eMerzh/slack_down#1]
I noticed this library doesn't have a license. Would it be possible to add one? E.g. MIT.

I'd be interested in making some modifications and potentially publishing the markdown extension on PyPi so it can be used by others.

**Comment by eMerzh** [comment]
Hey 👋 

thanks, you are correct, 
i've added a license (mit)... 
i should probably update this /o\ but had other stuff on my plate... 

i would still consider merging PR and improve things when i have more time

**Comment by czue** [comment]
awesome, thanks for the speedy response!
